services:
  postgres:
    image: postgres:18.4-alpine
    container_name: patient-flow-postgres-dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=patientflow
      - POSTGRES_PASSWORD=patientflow_dev_password
      - POSTGRES_DB=patientflow
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - patient-flow-dev

volumes:
  postgres_data:

networks:
  patient-flow-dev:
    driver: bridge
